baseURL: '/'
defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: true
title: InnerSource Commons

pluralizeListTitles: false
paginate: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
minify:
  disableHTML: true
uglyurls: false