baseURL: 'https://staging.iscf.site/'
defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: false
title: InnerSource Commons

pluralizeListTitles: false
pagination.pagerSize: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
minify:
  disableHTML: true
uglyurls: false

frontmatter:
  date:
  - report_publish_date
  - :default
outputs:
  home: ["HTML", "RSS", "JSON"]
