baseURL: 'https://innersourcecommons.org/'
defaultContentLanguage: 'en'
defaultContentLanguageInSubdir: false
params:
  # Redirect to default language if translation is missing
  redirectMissingTranslations: true

title: InnerSource Commons

pluralizeListTitles: false
pagination.pagerSize: '3'
summaryLength: '15'
disqusShortname: ''
googleAnalytics: ''
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
minify:
  disableHTML: true
uglyurls: false

frontmatter:
  date:
  - report_publish_date
  - :default
outputs:
  home: ["HTML", "RSS", "JSON"]
