baseURL: '/'
title: InnerSource Commons

pluralizeListTitles: false
paginate: '3'
summaryLength: '40'
disqusShortname: ''
googleAnalytics: ''
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
minify:
  disableHTML: true
defaultContentLanguage: 'en'
