en:
  languageName: English
  contentDir: content/en
  weight: 10
fr:
  languageName: Français
  contentDir: content/fr
  weight: 20
ja:
  languageName: 日本語
  contentDir: content/ja
  weight: 20
de:
  languageName: Deutsch
  contentDir: content/de
  weight: 30
es:
  languageName: Español
  contentDir: content/es
  weight: 30
it:
  languageName: Italiano
  contentDir: content/it
  weight: 30
pt-br:
  languageName: Português Brasileiro
  contentDir: content/pt-br
  weight: 30
ru:
  languageName: Русский
  contentDir: content/ru
  weight: 30
zh:
  languageName: 中文
  contentDir: content/zh
  weight: 30