main:
  - name: About
    URL: about
    weight: 1
    identifier: about
  - name: "我们是谁"
    URL: about
    parent: about
    weight: 2
  - name: "董事会与治理"
    URL: about/board
    parent: about
    weight: 3
  - name: "成员"
    URL: about/members
    parent: about
    weight: 4
  - name: "赞助商"
    URL: about/sponsors
    parent: about
    weight: 5
  - name: "InnerSource 故事"
    URL: stories
    parent: about
    weight: 6
  - name: GitHub
    URL: https://github.com/InnerSourceCommons
    parent: about
    weight: 7
  - name: "联系我们"
    URL: about/contact
    parent: about
    weight: 10
  - name: "行为准则"
    URL: about/codeofconduct
    parent: about
    weight: 11


# Projects
  - name: Activities
    URL: learn/patterns
    weight: 2
    identifier: activities
  - name: "活动"
    URL: /community
    parent: activities
    weight: 1
  - name: InnerSource Patterns Working Group
    URL: /learn/patterns
    parent: activities
    weight: 1
  - name: ISPO Working Group
    URL: /community/
    parent: activities
    weight: 2
  - name: Learning Path Working Group
    URL: /community/
    parent: activities
    weight: 3
  - name: Marketing & Outreach Working Group
    URL: /community/
    parent: activities
    weight: 4
  - name: "本地社区"
    URL: /community/
    parent: activities
    weight: 7
  - name: "InnerSource调查现状"
    URL: learn/research
    parent: activities
    weight: 8

## Learning
  - name: Learning
    URL: learn
    weight: 1
    identifier: learning
  - name: "学习"
    URL: learn/
    parent: learning
    weight: 1
  - name: "学习路径"
    URL: learn/learning-path
    parent: learning
    weight: 2
  - name: InnerSource Patterns
    URL: https://innersourcecommons.org/learn/books/innersource-patterns/
    parent: learning
    weight: 3
  - name: "管理InnerSource项目"
    URL: https://innersourcecommons.org/learn/books/managing-innersource-projects/
    parent: learning
    weight: 4
  - name: "视频"
    URL: https://www.youtube.com/@InnerSourceCommons
    parent: learning
    weight: 5
  - name: "书籍"
    URL: learn/books
    parent: learning
    weight: 6
  - name: "InnerSource入门"
    URL: https://innersourcecommons.org/learn/books/getting-started-with-innersource/
    parent: learning
    weight: 7
  - name: "理解InnerSource检查清单"
    URL: https://innersourcecommons.org/learn/books/understanding-the-innersource-checklist/
    parent: learning
    weight: 8
  - name: "采用InnerSource原则和案例研究"
    URL: https://innersourcecommons.org/learn/books/adopting-innersource-principles-and-case-studies/
    parent: learning
    weight: 9

# Community
  - name: Community
    URL: community
    weight: 4
    identifier: community
  - name: "社区会议"
    URL: events/community-calls
    parent: community
    weight: 1
    
  - name: "InnerSource聚会 - 本地分会"
    URL: https://gatherings.innersourcecommons.org/
    parent: community
    weight: 3
  - name: "InnerSource峰会2024"
    URL: events/isc-2024
    parent: community
    weight: 4
  - name: "往届峰会"
    URL: https://innersourcecommons.org/events/past-summits/
    parent: community
    weight: 5
  - name: "服务目录"
    URL: community/services
    parent: community
    weight: 10
  - name: "InnerSourcers地图"
    URL: about/map
    parent: community
    weight: 11

# News
  - name: News
    URL: about/announcements
    weight: 5
    identifier: news
  - name: "公告"
    URL: about/announcements
    parent: news
    weight: 1
  - name: "往期通讯"
    URL: https://us1.campaign-archive.com/home/?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2
    parent: news
    weight: 1

# Calendar
  - name: Schedule
    URL: #
    weight: 9
    identifier: schedule

footer_left:
  - name: "学习"
    URL: learn
    weight: 1
    post: bold
  - name: "书籍"
    URL: learn/books
    weight: 2
  - name: "学习路径"
    URL: learn/learning-path
    weight: 3
  - name: "模式"
    URL: learn/patterns
    weight: 4
  - name: "研究"
    URL: learn/research
    weight: 5
footer_middle:
  - name: "活动"
    URL: events/community-calls
    weight: 1
    post: bold
  - name: "2024峰会"
    URL: events/isc-2024
    weight: 2
  - name: "本地聚会"
    URL: https://gatherings.innersourcecommons.org/
    weight: 3
  - name: "往届峰会"
    URL: events/past-summits
    weight: 3
  - name: "社区"
    URL: community
    weight: 4
    post: bold
    pre: _blank
  - name: "故事"
    URL: stories
    weight: 5
    post: bold
  - name: "服务目录"
    URL: community/services
    weight: 6
  - name: "公告"
    URL: about/announcements
    weight: 7
footer_right:
  - name: "关于"
    URL: about
    weight: 1
    post: bold
  - name: "董事会与治理"
    URL: about/board
    weight: 2
  - name: "成员"
    URL: about/members
    weight: 3
  - name: "赞助商"
    URL: about/sponsors
    weight: 4
  - name: "行为准则"
    URL: about/codeofconduct
    weight: 5
  - name: "联系我们"
    URL: about/contact
    weight: 6
  - name: "隐私政策"
    URL: about/privacy
    weight: 7
