main:
  - name: Apprendre
    URL: fr/learn
    weight: 1
    identifier: learn
  - name: Livres
    parent: learn
    URL: fr/learn/books
    weight: 2
  - name: Parcours d'apprentissage
    parent: learn
    URL: fr/learn/learning-path
    weight: 3
  - name: Patterns
    parent: learn
    URL: fr/learn/patterns
    weight: 4
  - name: Recherche
    parent: learn
    URL: fr/learn/research
    weight: 5
  - name: Vidéos
    parent: learn
    URL: https://www.youtube.com/@InnerSourceCommons
    weight: 6
  - name: Évènements
    URL: fr/events/communitycalls
    weight: 2
  - name: Communauté
    identifier: community
    URL: fr/community
    weight: 3
  - name: Histoires
    URL: fr/stories
    weight: 4
  - name: Annuaire de Services
    URL: fr/community/services
    parent: community
    weight: 2
  - name: À Propos
    identifier: about
    URL: fr/about
    weight: 5
  - name: Annonces
    URL: fr/about/announcements
    parent: about
    weight: 1
  - name: Conseil d'Administration et de Gouvernance
    URL: fr/about/board
    parent: about
    weight: 2
  - name: Membres
    URL: fr/about/members
    parent: about
    weight: 3
  - name: Sponsors
    URL: fr/about/sponsors
    parent: about
    weight: 4
  - name: Code de Conduite
    URL: fr/about/codeofconduct
    parent: about
    weight: 5
  - name: Nous contacter
    URL: fr/about/contact
    parent: about
    weight: 6
  # - name: Postes vacants
  #   URL: fr/about/vacancies
  #   parent: about
  #   weight: 7
footer_left:
  - name: Apprendre
    URL: fr/learn
    weight: 1
    post: bold
  - name: Livres
    URL: fr/learn/books
    weight: 2
  - name: Parcours d'apprentissage
    URL: fr/learn/learning-path
    weight: 3
  - name: Patterns
    URL: fr/learn/patterns
    weight: 4
  - name: Recherche
    URL: fr/learn/research
    weight: 5
footer_middle:
  - name: Évènements
    URL: fr/events/communitycalls
    weight: 1
    post: bold
  - name: Communauté
    URL: fr/community
    weight: 2
    post: bold
    pre: _blank
  - name: Histoires
    URL: fr/stories
    weight: 3
    post: bold
  - name: Annuaire de Services
    URL: fr/community/services
    weight: 4
  - name: Annonces
    URL: fr/about/announcements
    weight: 5
footer_right:
  - name: À Propos
    URL: fr/about
    weight: 1
    post: bold
  - name: Conseil d'Administration et de Gouvernance
    URL: fr/about/board
    weight: 2
  - name: Membres
    URL: fr/about/members
    weight: 3
  - name: Sponsors
    URL: fr/about/sponsors
    weight: 4
  - name: Code de Conduite
    URL: fr/about/codeofconduct
    weight: 5
  - name: Nous contacter
    URL: fr/about/contact
    weight: 6
  - name: Politique de confidentialité
    URL: fr/about/privacy
    weight: 7
  # - name: Postes vacants
  #   URL: fr/about/vacancies
  #   weight: 8