main:
  # Start Here
  - name: Start Here
    weight: 1
    identifier: start-here
  - name: Get involved
    URL: https://innersourcecommons.org/community/
    parent: start-here
    weight: 1
  - name: Summit 2025
    URL: https://innersourcecommons.org/events/isc-2025/
    parent: start-here
    weight: 2
  - name: Community and Events
    URL: https://innersourcecommons.org/events/community-calls/
    parent: start-here
    weight: 2
  - name: Check out Our Repositories
    URL: https://github.com/InnerSourceCommons
    parent: start-here
    weight: 3
  - name: Join our Chat on Slack
    URL: https://innersourcecommons.org/slack
    parent: start-here
    weight: 4
  - name: Join our Mailing List
    URL: https://innersourcecommons.us1.list-manage.com/subscribe?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2
    parent: start-here
    weight: 5

  # About
  - name: About
    weight: 2
    identifier: about
  - name: Who We Are
    URL: https://innersourcecommons.org/about/
    parent: about
    weight: 1
  - name: Board & Governance
    URL: https://innersourcecommons.org/about/board/
    parent: about
    weight: 2
  - name: Members
    URL: https://innersourcecommons.org/about/members/
    parent: about
    weight: 3
  - name: Sponsors
    URL: https://innersourcecommons.org/about/sponsors/
    parent: about
    weight: 4
  - name: Code of Conduct
    URL: https://innersourcecommons.org/about/codeofconduct/
    parent: about
    weight: 5
  - name: Vacancies
    URL: https://innersourcecommons.org/about/vacancies/
    parent: about
    weight: 6
  - name: Get in Touch
    URL: https://innersourcecommons.org/about/contact/
    parent: about
    weight: 7

  # Community
  - name: Community
    weight: 3
    identifier: community
  - name: Join us on Slack
    URL: https://innersourcecommons.org/slack
    parent: community
    weight: 1
  - name: Working Groups
    URL: https://innersourcecommons.org/community/
    parent: community
    weight: 2
  - name: Case Studies
    URL: https://innersourcecommons.org/stories/microsoft/
    parent: community
    weight: 3
  - name: Services Directory
    URL: https://innersourcecommons.org/community/services/
    parent: community
    weight: 4
  - name: Code of Conduct
    URL: https://innersourcecommons.org/about/codeofconduct/
    parent: community
    weight: 5

  # Learning (Mega Menu)
  - name: Learning
    weight: 4
    identifier: learning
  # Learning Resources Column
  - name: InnerSource Patterns ⭐
    URL: https://innersourcecommons.org/learn/books/innersource-patterns/
    parent: learning
    weight: 1
    params:
      column: resources
  - name: Learning Path
    URL: https://innersourcecommons.org/learn/learning-path/
    parent: learning
    weight: 2
    params:
      column: resources
  - name: InnerSource Stories
    URL: https://innersourcecommons.org/stories/microsoft/
    parent: learning
    weight: 3
    params:
      column: resources
  - name: Community Videos
    URL: https://www.youtube.com/@InnerSourceCommons
    parent: learning
    weight: 4
    params:
      column: resources
  # Books Column
  - name: Getting Started with InnerSource
    URL: https://innersourcecommons.org/learn/books/getting-started-with-innersource/
    parent: learning
    weight: 5
    params:
      column: books
  - name: Understanding the InnerSource Checklist
    URL: https://innersourcecommons.org/learn/books/understanding-the-innersource-checklist/
    parent: learning
    weight: 6
    params:
      column: books
  - name: Managing InnerSource Projects
    URL: https://innersourcecommons.org/learn/books/managing-innersource-projects/
    parent: learning
    weight: 7
    params:
      column: books
  - name: Adopting InnerSource
    URL: https://innersourcecommons.org/learn/books/adopting-innersource-principles-and-case-studies/
    parent: learning
    weight: 8
    params:
      column: books
  - name: See All Books
    URL: https://innersourcecommons.org/learn/books/
    parent: learning
    weight: 9
    params:
      column: books

  # Events (Mega Menu)
  - name: Events
    weight: 5
    identifier: events
  # General Info Column
  - name: Upcoming Events
    URL: https://innersourcecommons.org/events/community-calls/
    parent: events
    weight: 1
    params:
      column: general
  - name: Events Calendar
    URL: https://calendar.google.com/calendar/embed?src=c_62694f414055ac569e5cb12dafbb0890ca22f3640b177a4b10b53171fbc9bdd4%40group.calendar.google.com&ctz=Europe%2FDublin
    parent: events
    weight: 2
    params:
      column: general
  - name: Past Event Recordings
    URL: https://www.youtube.com/@InnerSourceCommons
    parent: events
    weight: 3
    params:
      column: general
  # Event Types Column
  - name: Community Calls
    URL: https://innersourcecommons.org/events/community-calls/
    parent: events
    weight: 4
    params:
      column: types
  - name: Gatherings - Local Chapters
    URL: https://gatherings.innersourcecommons.org/
    parent: events
    weight: 5
    params:
      column: types
  - name: InnerSource Summit 2025
    URL: https://innersourcecommons.org/events/isc-2025/
    parent: events
    weight: 6
    params:
      column: types
  - name: InnerSource Past Summits
    URL: https://innersourcecommons.org/events/past-summits/
    parent: events
    weight: 7
    params:
      column: types

  # News & Updates
  - name: News & Updates
    weight: 6
    identifier: news
  - name: Announcements
    URL: https://innersourcecommons.org/about/announcements/
    parent: news
    weight: 1
  - name: Newsletters
    URL: https://us1.campaign-archive.com/home/?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2
    parent: news
    weight: 2
  - name: Newsletter Signup
    URL: https://innersourcecommons.us1.list-manage.com/subscribe?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2
    parent: news
    weight: 3
  - name: Submit an Article
    URL: mailto:marketing@innersourcecommons.org
    parent: news
    weight: 4

footer_left:
  - name: Learn
    URL: learn
    weight: 1
    post: bold
  - name: Books
    URL: learn/books
    weight: 2
  - name: Learning Path
    URL: learn/learning-path
    weight: 3
  - name: Patterns
    URL: learn/patterns
    weight: 4
  - name: Research
    URL: learn/research
    weight: 5
footer_middle:
  - name: Events
    URL: events/community-calls
    weight: 1
    post: bold
  - name: Summit 2025
    URL: events/isc-2025
    weight: 2
  - name: Local Gatherings
    URL: https://gatherings.innersourcecommons.org/
    weight: 3
  - name: Past Summits
    URL: events/past-summits
    weight: 3
  - name: Community
    URL: community
    weight: 4
    post: bold
    pre: _blank
  - name: Stories
    URL: stories
    weight: 5
    post: bold
  - name: Services Directory
    URL: community/services
    weight: 6
  - name: Announcements
    URL: about/announcements
    weight: 7
footer_right:
  - name: About
    URL: about
    weight: 1
    post: bold
  - name: Board & Governance
    URL: about/board
    weight: 2
  - name: Members
    URL: about/members
    weight: 3
  - name: Sponsors
    URL: about/sponsors
    weight: 4
  - name: Code of Conduct
    URL: about/codeofconduct
    weight: 5
  - name: Contact Us
    URL: about/contact
    weight: 6
  - name: Privacy Policy
    URL: about/privacy
    weight: 7
  # - name: Vacancies
  #   URL: about/vacancies
  #   weight: 8
