main:
  - name: About
    URL: about
    weight: 1
    identifier: about
  - name: "Chi siamo"
    URL: about
    parent: about
    weight: 2
  - name: "Consiglio & Governance"
    URL: about/board
    parent: about
    weight: 3
  - name: "Membri"
    URL: about/members
    parent: about
    weight: 4
  - name: "Sponsor"
    URL: about/sponsors
    parent: about
    weight: 5
  - name: "Storie InnerSource"
    URL: stories
    parent: about
    weight: 6
  - name: GitHub
    URL: https://github.com/InnerSourceCommons
    parent: about
    weight: 7
  - name: "Contattaci"
    URL: about/contact
    parent: about
    weight: 10
  - name: "Codice di Condotta"
    URL: about/codeofconduct
    parent: about
    weight: 11


# Projects
  - name: Activities
    URL: learn/patterns
    weight: 2
    identifier: activities
  - name: "Attività"
    URL: /community
    parent: activities
    weight: 1
  - name: InnerSource Patterns Working Group
    URL: /learn/patterns
    parent: activities
    weight: 1
  - name: ISPO Working Group
    URL: /community/
    parent: activities
    weight: 2
  - name: Learning Path Working Group
    URL: /community/
    parent: activities
    weight: 3
  - name: Marketing & Outreach Working Group
    URL: /community/
    parent: activities
    weight: 4
  - name: "Comunità Locale"
    URL: /community/
    parent: activities
    weight: 7
  - name: "Stato del Sondaggio InnerSource"
    URL: learn/research
    parent: activities
    weight: 8

## Learning
  - name: Learning
    URL: learn
    weight: 1
    identifier: learning
  - name: "Apprendimento"
    URL: learn/
    parent: learning
    weight: 1
  - name: "Percorso di Apprendimento"
    URL: learn/learning-path
    parent: learning
    weight: 2
  - name: InnerSource Patterns
    URL: https://innersourcecommons.org/learn/books/innersource-patterns/
    parent: learning
    weight: 3
  - name: "Gestione dei Progetti InnerSource"
    URL: https://innersourcecommons.org/learn/books/managing-innersource-projects/
    parent: learning
    weight: 4
  - name: "Video"
    URL: https://www.youtube.com/@InnerSourceCommons
    parent: learning
    weight: 5
  - name: "Libri"
    URL: learn/books
    parent: learning
    weight: 6
  - name: "Iniziare con InnerSource"
    URL: https://innersourcecommons.org/learn/books/getting-started-with-innersource/
    parent: learning
    weight: 7
  - name: "Comprendere la Checklist InnerSource"
    URL: https://innersourcecommons.org/learn/books/understanding-the-innersource-checklist/
    parent: learning
    weight: 8
  - name: "Adozione dei Principi e Casi Studio InnerSource"
    URL: https://innersourcecommons.org/learn/books/adopting-innersource-principles-and-case-studies/
    parent: learning
    weight: 9

# Community
  - name: Community
    URL: community
    weight: 4
    identifier: community
  - name: "Chiamate della Comunità"
    URL: events/community-calls
    parent: community
    weight: 1
    
  - name: "Incontri InnerSource - Capitoli Locali"
    URL: https://gatherings.innersourcecommons.org/
    parent: community
    weight: 3
  - name: "Summit InnerSource 2024"
    URL: events/isc-2024
    parent: community
    weight: 4
  - name: "Summit Precedenti"
    URL: https://innersourcecommons.org/events/past-summits/
    parent: community
    weight: 5
  - name: "Elenco dei Servizi"
    URL: community/services
    parent: community
    weight: 10
  - name: "Mappa degli InnerSourcers"
    URL: about/map
    parent: community
    weight: 11

# News
  - name: Blog & News
    URL: about/announcements
    weight: 5
    identifier: news
  - name: "Annunci"
    URL: about/announcements
    parent: news
    weight: 1
  - name: "Newsletter Precedenti"
    URL: https://us1.campaign-archive.com/home/?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2
    parent: news
    weight: 1

# Calendar
  - name: Schedule
    URL: #
    weight: 9
    identifier: schedule

footer_left:
  - name: "Apprendimento"
    URL: learn
    weight: 1
    post: bold
  - name: "Libri"
    URL: learn/books
    weight: 2
  - name: "Percorso di Apprendimento"
    URL: learn/learning-path
    weight: 3
  - name: "Modelli"
    URL: learn/patterns
    weight: 4
  - name: "Ricerca"
    URL: learn/research
    weight: 5
footer_middle:
  - name: "Eventi"
    URL: events/community-calls
    weight: 1
    post: bold
  - name: "Summit 2024"
    URL: events/isc-2024
    weight: 2
  - name: "Incontri Locali"
    URL: https://gatherings.innersourcecommons.org/
    weight: 3
  - name: "Summit Precedenti"
    URL: events/past-summits
    weight: 3
  - name: "Comunità"
    URL: community
    weight: 4
    post: bold
    pre: _blank
  - name: "Storie"
    URL: stories
    weight: 5
    post: bold
  - name: "Elenco dei Servizi"
    URL: community/services
    weight: 6
  - name: "Annunci"
    URL: about/announcements
    weight: 7
footer_right:
  - name: "Chi siamo"
    URL: about
    weight: 1
    post: bold
  - name: "Consiglio & Governance"
    URL: about/board
    weight: 2
  - name: "Membri"
    URL: about/members
    weight: 3
  - name: "Sponsor"
    URL: about/sponsors
    weight: 4
  - name: "Codice di Condotta"
    URL: about/codeofconduct
    weight: 5
  - name: "Contattaci"
    URL: about/contact
    weight: 6
  - name: "Informativa sulla Privacy"
    URL: about/privacy
    weight: 7
  # - name: "Posizioni Aperte"
  #   URL: about/vacancies
  #   weight: 8