main:
  - name: Aprender
    URL: pt-br/learn
    weight: 1
    identifier: learn
  - name: Livros
    parent: learn
    URL: pt-br/learn/books
    weight: 2
  - name: Caminho de Aprendizado
    parent: learn
    URL: pt-br/learn/learning-path
    weight: 3
  - name: Padrões
    parent: learn
    URL: pt-br/learn/patterns
    weight: 4
  - name: Pesquisa
    parent: learn
    URL: pt-br/learn/research
    weight: 5
  - name: Eventos
    URL: pt-br/events
    weight: 2
  - name: Comunidade
    identifier: community
    URL: pt-br/community
    weight: 3
  - name: Histórias
    URL: pt-br/stories
    weight: 4
  - name: Diretório de Serviços
    URL: pt-br/community/services
    parent: community
    weight: 2
  - name: Sobre
    identifier: about
    URL: pt-br/about
    weight: 5
  - name: Anúncios
    URL: pt-br/about/announcements
    parent: about
    weight: 1
  - name: Diretoria e Governança
    URL: pt-br/about/board
    parent: about
    weight: 2
  - name: Membros
    URL: pt-br/about/members
    parent: about
    weight: 3
  - name: Patrocinadores
    URL: pt-br/about/sponsors
    parent: about
    weight: 4
  - name: Código de Conduta
    URL: pt-br/about/codeofconduct
    parent: about
    weight: 5
  - name: Fale Conosco
    URL: pt-br/about/contact
    parent: about
    weight: 6
footer_left:
  - name: Aprender
    URL: pt-br/learn
    weight: 1
    post: bold
  - name: Livros
    URL: pt-br/learn/books
    weight: 2
  - name: Caminho de Aprendizado
    URL: pt-br/learn/learning-path
    weight: 3
  - name: Padrões
    URL: pt-br/learn/patterns
    weight: 4
  - name: Pesquisa
    URL: pt-br/learn/research
    weight: 5
footer_middle:
  - name: Eventos
    URL: pt-br/events
    weight: 1
    post: bold
  - name: Comunidade
    URL: pt-br/community
    weight: 2
    post: bold
    pre: _blank
  - name: Histórias
    URL: pt-br/stories
    weight: 3
    post: bold
  - name: Diretório de Serviços
    URL: pt-br/community/services
    weight: 4
  - name: Anúncios
    URL: pt-br/about/announcements
    weight: 5
footer_right:
  - name: Sobre
    URL: pt-br/about
    weight: 1
    post: bold
  - name: Diretoria e Governança
    URL: pt-br/about/board
    weight: 2
  - name: Membros
    URL: pt-br/about/members
    weight: 3
  - name: Patrocinadores
    URL: pt-br/about/sponsors
    weight: 4
  - name: Código de Conduta
    URL: pt-br/about/codeofconduct
    weight: 5
  - name: Fale Conosco
    URL: pt-br/about/contact
    weight: 6
  - name: Política de Privacidade
    URL: pt-br/about/privacy
    weight: 7
