main:
  - name: Learn
    URL: learn
    weight: 1
    identifier: learn
  - name: Books
    parent: learn
    URL: learn/books
    weight: 2
  - name: Learning Path
    parent: learn
    URL: learn/learning-path
    weight: 3
  - name: Patterns
    parent: learn
    URL: learn/patterns
    weight: 4
  - name: Research
    parent: learn
    URL: learn/research
    weight: 5
  - name: Events
    URL: events/community-calls
    weight: 2
    identifier: events
  - name: Summit 2024
    URL: events/isc-2024
    parent: events
    weight: 4
  - name: Local Gatherings
    URL: https://gatherings.innersourcecommons.org/
    parent: events
    weight: 5
  - name: Community Calls
    URL: events/community-calls
    parent: events
    weight: 6
  - name: Past Summits
    URL: events/past-summits
    parent: events
    weight: 7
  - name: Calendar
    URL: calendar
    weight: 3
  - name: Community
    identifier: community
    URL: community
    weight: 4
  - name: Stories
    URL: stories
    weight: 5
  - name: Services Directory
    URL: community/services
    parent: community
    weight: 2
  - name: About
    identifier: about
    URL: about
    weight: 6
  - name: Announcements
    URL: about/announcements
    parent: about
    weight: 1
  - name: Board & Governance
    URL: about/board
    parent: about
    weight: 2
  - name: Members
    URL: about/members
    parent: about
    weight: 3
  - name: Sponsors
    URL: about/sponsors
    parent: about
    weight: 4
  - name: Code of Conduct
    URL: about/codeofconduct
    parent: about
    weight: 5
  - name: Contact Us
    URL: about/contact
    parent: about
    weight: 6
  # - name: Vacancies
  #   URL: about/vacancies
  #   parent: about
  #   weight: 7
footer_left:
  - name: Learn
    URL: learn
    weight: 1
    post: bold
  - name: Books
    URL: learn/books
    weight: 2
  - name: Learning Path
    URL: learn/learning-path
    weight: 3
  - name: Patterns
    URL: learn/patterns
    weight: 4
  - name: Research
    URL: learn/research
    weight: 5
footer_middle:
  - name: Events
    URL: events/community-calls
    weight: 1
    post: bold
  - name: Summit 2024
    URL: events/isc-2024
    weight: 2
  - name: Local Gatherings
    URL: https://gatherings.innersourcecommons.org/
    weight: 3
  - name: Past Summits
    URL: events/past-summits
    weight: 3
  - name: Community
    URL: community
    weight: 4
    post: bold
    pre: _blank
  - name: Stories
    URL: stories
    weight: 5
    post: bold
  - name: Services Directory
    URL: community/services
    weight: 6
  - name: Announcements
    URL: about/announcements
    weight: 7
footer_right:
  - name: About
    URL: about
    weight: 1
    post: bold
  - name: Board & Governance
    URL: about/board
    weight: 2
  - name: Members
    URL: about/members
    weight: 3
  - name: Sponsors
    URL: about/sponsors
    weight: 4
  - name: Code of Conduct
    URL: about/codeofconduct
    weight: 5
  - name: Contact Us
    URL: about/contact
    weight: 6
  - name: Privacy Policy
    URL: about/privacy
    weight: 7
  # - name: Vacancies
  #   URL: about/vacancies
  #   weight: 8