main:
- name: 学ぶ
  URL: ja/learn
  weight: 1
  identifier: learn
- name: 関連書籍
  parent: learn
  URL: ja/learn/books
  weight: 2
- name: ラーニングパス
  parent: learn
  URL: ja/learn/learning-path
  weight: 3
- name: インナーソースパターン
  parent: learn
  URL: ja/learn/patterns
  weight: 4
- name: リサーチ
  parent: learn
  URL: ja/learn/research
  weight: 5
- name: ビデオ
  parent: learn
  URL: https://www.youtube.com/@InnerSourceCommons
  weight: 6
- name: イベント
  URL: ja/events/community-calls
  weight: 2
- name: コミュニティ
  identifier: community
  URL: ja/community
  weight: 3
- name: 事例
  URL: ja/stories
  weight: 4
- name: 提供企業
  URL: ja/community/services
  parent: community
  weight: 2
- name: About
  identifier: about
  URL: ja/about
  weight: 5
- name: アナウンス
  URL: ja/about/announcements
  parent: about
  weight: 1
- name: 役員とガバナンス
  URL: ja/about/board
  parent: about
  weight: 2
- name: メンバーについて
  URL: ja/about/members
  parent: about
  weight: 3
- name: スポンサー
  URL: ja/about/sponsors
  parent: about
  weight: 4
- name: 行動規範
  URL: ja/about/codeofconduct
  parent: about
  weight: 5
- name: お問合せ
  URL: ja/about/contact
  parent: about
  weight: 6
# - name: 欠員
#   URL: ja/about/vacancies
#   parent: about
#   weight: 7
footer_left:
- name: 学ぶ
  URL: ja/learn
  weight: 1
  post: bold
- name: 関連書籍
  URL: ja/learn/books
  weight: 2
- name: ラーニングパス
  URL: ja/learn/learning-path
  weight: 3
- name: インナーソースパターン
  URL: ja/learn/patterns
  weight: 4
- name: リサーチ
  URL: ja/learn/research
  weight: 5
footer_middle:
- name: イベント
  URL: ja/events/community-calls
  weight: 1
  post: bold
- name: コミュニティ
  URL: ja/community
  weight: 2
  post: bold
  pre: _blank
- name: 事例
  URL: ja/stories
  weight: 3
  post: bold
- name: 提供企業
  URL: ja/community/services
  weight: 4
- name: アナウンス
  URL: ja/about/announcements
  weight: 5
footer_right:
- name: About
  URL: ja/about
  weight: 1
  post: bold
- name: 役員とガバナンス
  URL: ja/about/board
  weight: 2
- name: メンバーについて
  URL: ja/about/members
  weight: 3
- name: スポンサー
  URL: ja/about/sponsors
  weight: 4
- name: 行動規範
  URL: ja/about/codeofconduct
  weight: 5
- name: お問合せ
  URL: ja/about/contact
  weight: 6
- name: プライバシーポリシー
  URL: ja/about/privacy
  weight: 7
# - name: 欠員
#   URL: ja/about/vacancies
#   weight: 8