main:
  - name: Learn
    URL: es/learn
    weight: 1
    identifier: learn
  - name: Books
    parent: learn
    URL: es/learn/books
    weight: 2
  - name: Learning Path
    parent: learn
    URL: es/learn/learning-path
    weight: 3
  - name: Patterns
    parent: learn
    URL: es/learn/patterns
    weight: 4
  - name: Research
    parent: learn
    URL: es/learn/research
    weight: 5
  - name: Events
    URL: es/events/community-calls
    weight: 2
  - name: Community
    identifier: community
    URL: es/community
    weight: 3
  - name: Stories
    URL: es/stories
    weight: 4
  - name: Services Directory
    URL: es/community/services
    parent: community
    weight: 2
  - name: About
    identifier: about
    URL: es/about
    weight: 5
  - name: Announcements
    URL: es/about/announcements
    parent: about
    weight: 1
  - name: Board & Governance
    URL: es/about/board
    parent: about
    weight: 2
  - name: Members
    URL: es/about/members
    parent: about
    weight: 3
  - name: Sponsors
    URL: es/about/sponsors
    parent: about
    weight: 4
  - name: Code of Conduct
    URL: es/about/codeofconduct
    parent: about
    weight: 5
  - name: Contact Us
    URL: es/about/contact
    parent: about
    weight: 6
footer_left:
  - name: Learn
    URL: es/learn
    weight: 1
    post: bold
  - name: Books
    URL: es/learn/books
    weight: 2
  - name: Learning Path
    URL: es/learn/learning-path
    weight: 3
  - name: Patterns
    URL: es/learn/patterns
    weight: 4
  - name: Research
    URL: es/learn/research
    weight: 5
footer_middle:
  - name: Events
    URL: es/events/community-calls
    weight: 1
    post: bold
  - name: Community
    URL: es/community
    weight: 2
    post: bold
    pre: _blank
  - name: Stories
    URL: es/stories
    weight: 3
    post: bold
  - name: Services Directory
    URL: es/community/services
    weight: 4
  - name: Announcements
    URL: es/about/announcements
    weight: 5
footer_right:
  - name: About
    URL: es/about
    weight: 1
    post: bold
  - name: Board & Governance
    URL: es/about/board
    weight: 2
  - name: Members
    URL: es/about/members
    weight: 3
  - name: Sponsors
    URL: es/about/sponsors
    weight: 4
  - name: Code of Conduct
    URL: es/about/codeofconduct
    weight: 5
  - name: Contact Us
    URL: es/about/contact
    weight: 6
  - name: Privacy Policy
    URL: es/about/privacy
    weight: 7