main:
  - name: About
    URL: about
    weight: 1
    identifier: about
  - name: "Quem Somos"
    URL: about
    parent: about
    weight: 2
  - name: "Conselho & Governança"
    URL: about/board
    parent: about
    weight: 3
  - name: "Membros"
    URL: about/members
    parent: about
    weight: 4
  - name: "Patrocinadores"
    URL: about/sponsors
    parent: about
    weight: 5
  - name: "Histórias InnerSource"
    URL: stories
    parent: about
    weight: 6
  - name: GitHub
    URL: https://github.com/InnerSourceCommons
    parent: about
    weight: 7
  - name: "Contate-nos"
    URL: about/contact
    parent: about
    weight: 10
  - name: "Código de Conduta"
    URL: about/codeofconduct
    parent: about
    weight: 11


# Projects
  - name: Activities
    URL: learn/patterns
    weight: 2
    identifier: activities
  - name: "Atividades"
    URL: /community
    parent: activities
    weight: 1
  - name: InnerSource Patterns Working Group
    URL: /learn/patterns
    parent: activities
    weight: 1
  - name: ISPO Working Group
    URL: /community/
    parent: activities
    weight: 2
  - name: Learning Path Working Group
    URL: /community/
    parent: activities
    weight: 3
  - name: Marketing & Outreach Working Group
    URL: /community/
    parent: activities
    weight: 4
  - name: "Comunidade Local"
    URL: /community/
    parent: activities
    weight: 7
  - name: "Estado da Pesquisa InnerSource"
    URL: learn/research
    parent: activities
    weight: 8

## Learning
  - name: Learning
    URL: learn
    weight: 1
    identifier: learning
  - name: "Aprendizado"
    URL: learn/
    parent: learning
    weight: 1
  - name: "Trilha de Aprendizado"
    URL: learn/learning-path
    parent: learning
    weight: 2
  - name: InnerSource Patterns
    URL: https://innersourcecommons.org/learn/books/innersource-patterns/
    parent: learning
    weight: 3
  - name: "Gerenciando Projetos InnerSource"
    URL: https://innersourcecommons.org/learn/books/managing-innersource-projects/
    parent: learning
    weight: 4
  - name: "Vídeos"
    URL: https://www.youtube.com/@InnerSourceCommons
    parent: learning
    weight: 5
  - name: "Livros"
    URL: learn/books
    parent: learning
    weight: 6
  - name: "Começando com InnerSource"
    URL: https://innersourcecommons.org/learn/books/getting-started-with-innersource/
    parent: learning
    weight: 7
  - name: "Entendendo a Lista de Verificação InnerSource"
    URL: https://innersourcecommons.org/learn/books/understanding-the-innersource-checklist/
    parent: learning
    weight: 8
  - name: "Adotando Princípios e Estudos de Caso InnerSource"
    URL: https://innersourcecommons.org/learn/books/adopting-innersource-principles-and-case-studies/
    parent: learning
    weight: 9

# Community
  - name: Community
    URL: community
    weight: 4
    identifier: community
  - name: "Chamadas da Comunidade"
    URL: events/community-calls
    parent: community
    weight: 1
    
  - name: "Encontros InnerSource - Capítulos Locais"
    URL: https://gatherings.innersourcecommons.org/
    parent: community
    weight: 3
  - name: "Summit InnerSource 2024"
    URL: events/isc-2024
    parent: community
    weight: 4
  - name: "Summits Anteriores"
    URL: https://innersourcecommons.org/events/past-summits/
    parent: community
    weight: 5
  - name: "Diretório de Serviços"
    URL: community/services
    parent: community
    weight: 10
  - name: "Mapa dos InnerSourcers"
    URL: about/map
    parent: community
    weight: 11

# News
  - name: News
    URL: about/announcements
    weight: 5
    identifier: news
  - name: "Anúncios"
    URL: about/announcements
    parent: news
    weight: 1
  - name: "Newsletters Anteriores"
    URL: https://us1.campaign-archive.com/home/?u=0363fb06e6a59d48c6e260f1b&id=97224b5ff2
    parent: news
    weight: 1

# Calendar
  - name: Schedule
    URL: #
    weight: 9
    identifier: schedule

footer_left:
  - name: "Aprendizado"
    URL: learn
    weight: 1
    post: bold
  - name: "Livros"
    URL: learn/books
    weight: 2
  - name: "Trilha de Aprendizado"
    URL: learn/learning-path
    weight: 3
  - name: "Padrões"
    URL: learn/patterns
    weight: 4
  - name: "Pesquisa"
    URL: learn/research
    weight: 5
footer_middle:
  - name: "Eventos"
    URL: events/community-calls
    weight: 1
    post: bold
  - name: "Summit 2024"
    URL: events/isc-2024
    weight: 2
  - name: "Encontros Locais"
    URL: https://gatherings.innersourcecommons.org/
    weight: 3
  - name: "Summits Anteriores"
    URL: events/past-summits
    weight: 3
  - name: "Comunidade"
    URL: community
    weight: 4
    post: bold
    pre: _blank
  - name: "Histórias"
    URL: stories
    weight: 5
    post: bold
  - name: "Diretório de Serviços"
    URL: community/services
    weight: 6
  - name: "Anúncios"
    URL: about/announcements
    weight: 7
footer_right:
  - name: "Sobre"
    URL: about
    weight: 1
    post: bold
  - name: "Conselho & Governança"
    URL: about/board
    weight: 2
  - name: "Membros"
    URL: about/members
    weight: 3
  - name: "Patrocinadores"
    URL: about/sponsors
    weight: 4
  - name: "Código de Conduta"
    URL: about/codeofconduct
    weight: 5
  - name: "Contate-nos"
    URL: about/contact
    weight: 6
  - name: "Política de Privacidade"
    URL: about/privacy
    weight: 7
  # - name: "Vagas"
  #   URL: about/vacancies
  #   weight: 8