main:
  - name: Lernen
    URL: de/learn
    weight: 1
    identifier: learn
  - name: Bücher
    parent: learn
    URL: de/learn/books
    weight: 2
  - name: Lernpfad
    parent: learn
    URL: de/learn/learning-path
    weight: 3
  - name: Muster
    parent: learn
    URL: de/learn/patterns
    weight: 4
  - name: Forschung
    parent: learn
    URL: de/learn/research
    weight: 5
  - name: Videos
    parent: learn
    URL: https://www.youtube.com/@InnerSourceCommons
    weight: 6
  - name: Ereignisse
    URL: de/events/community-calls
    weight: 2
  - name: Gemeinschaft
    identifier: community
    URL: de/community
    weight: 3
  - name: Geschichten
    URL: de/stories
    weight: 4
  - name: Diensteverzeichnis
    URL: de/community/services
    parent: community
    weight: 2
  - name: Über
    identifier: about
    URL: de/about
    weight: 5
  - name: Ankündigungen
    URL: de/about/announcements
    parent: about
    weight: 1
  - name: Board & Governance
    URL: de/about/board
    parent: about
    weight: 2
  - name: Mitglieder
    URL: de/about/members
    parent: about
    weight: 3
  - name: Sponsoren
    URL: de/about/sponsors
    parent: about
    weight: 4
  - name: Verhaltenskodex
    URL: de/about/codeofconduct
    parent: about
    weight: 5
  - name: Kontaktiere uns
    URL: de/about/contact
    parent: about
    weight: 6
footer_left:
  - name: Lernen
    URL: de/learn
    weight: 1
    post: bold
  - name: Bücher
    URL: de/learn/books
    weight: 2
  - name: Lernpfad
    URL: de/learn/learning-path
    weight: 3
  - name: Muster
    URL: de/learn/patterns
    weight: 4
  - name: Forschung
    URL: de/learn/research
    weight: 5
footer_middle:
  - name: Ereignisse
    URL: de/events/community-calls
    weight: 1
    post: bold
  - name: Gemeinschaft
    URL: de/community
    weight: 2
    post: bold
    pre: _blank
  - name: Geschichten
    URL: de/stories
    weight: 3
    post: bold
  - name: Diensteverzeichnis
    URL: de/community/services
    weight: 4
  - name: Ankündigungen
    URL: de/about/announcements
    weight: 5
footer_right:
  - name: Über
    URL: de/about
    weight: 1
    post: bold
  - name: Board & Governance
    URL: de/about/board
    weight: 2
  - name: Mitglieder
    URL: de/about/members
    weight: 3
  - name: Sponsoren
    URL: de/about/sponsors
    weight: 4
  - name: Verhaltenskodex
    URL: de/about/codeofconduct
    weight: 5
  - name: Kontaktiere uns
    URL: de/about/contact
    weight: 6
  - name: Datenschutz-Bestimmungen
    URL: de/about/privacy
    weight: 7
