plugins:
  css:
    - link: plugins/bootstrap/bootstrap.min.css
    - link: plugins/themify-icons/themify-icons.css
    - link: plugins/slick/slick.css
    - link: plugins/youmax/youmax.css
    - link: plugins/bootstrap-select/css/bootstrap-select.min.css
    - link: css/custom-menu.css
  js:
    - link: plugins/jQuery/jquery.min.js
    - link: plugins/bootstrap/bootstrap.min.js
    - link: plugins/slick/slick.min.js
    - link: plugins/youmax/youmax.js
    - link: plugins/bootstrap-select/js/bootstrap-select.min.js
logo: images/logo.png
mobileLogo: images/logo-big.png
themeVariant: quizdown
description: The InnerSource Commons is a growing community of practitioners with the goal of creating and sharing knowledge about InnerSource.
author: InnerSource Commons
defaultImage: images/logo.png
copyright: >-
  © InnerSource Commons Foundation 
preloader:
  enable: false
  preloader: ''
navigation_button:
  enable: true
  label: Join Slack
  link: slack
social:
  - title: github
    icon: ti-github
    link: 'http://github.com/InnerSourceCommons'
  - title: youtube
    icon: ti-youtube
    link: 'https://www.youtube.com/channel/UCoSPSd6Or4F_vpjo4SmyoEA'
  - title: twitter
    icon: ti-twitter-alt
    link: 'http://twitter.com/InnerSourceOrg'
  - title: linkedin
    icon: ti-linkedin
    link: 'https://linkedin.com/company/innersourcecommons'